### ISSUE TITLE
Could not connect to instruments

### ISSUE THREAD

**Issue by MaddoW** [Kamiooorek/myDLTS#1]
Hello,

we just tried to make the software running to try it out. Unfortunatly we could not establish a connection to the tools. The MFIA is connected via ethernet and the LakeShore331 is connected via GPIB. Both tools can be controlled by python, so the connection to the PC is fine.
![connection_error_LS331](https://github.com/Kamiooorek/myDLTS/assets/37832419/a8c2d50a-201c-4863-9841-2fd8421285ce)
![connection_error_MFIA](https://github.com/Kamiooorek/myDLTS/assets/37832419/e585faba-3443-454c-834e-6f1b6ab75b4e)
Best regards,
Malte

**Comment by Kamiooorek** [comment]
Hi!
I'm glad to see there's interest in the software.
Let's try to tackle both connection problems separately.

1. Temperature controllers other than LS325 have not been tested, since we simply don't have access to them. They probably require some debugging, although I'm surprised that even the connection fails. In the Settings menu, did the 'VISA Name' field auto-detect and list available GPIB devices?

2. Some versions of the MFIA firmware are fussy about connections from LabVIEW API especially via Ethernet. In my experience, sometimes it will only connect if LabOne is just running in the background, sometimes only if it's not running and sometimes only if LabOne is running and actively connected to the MFIA in the web interface. Please try recreating those situations.

Please attach your settings file (C:/ProgramData/myDLTS/settings.xml), so that we can rule out a config problem.

Sincerely,
Adrian Kaim

**Comment by MaddoW** [comment]
Hi :)
Thank you very much much for making the software  👍 

So we tried some stuff last week, to fix the conenction problems.

1.  Yes the Temperature Controller gets detected by the software and can be selected in the dropdown menu and is selected in all dropdown menus of the different tool-tabs. It is connected via GPIB PCI card in our PC and is on adress 12. The name is LakeShore331. What else can we try to make the connection work? :)
![lakeshore331_1](https://github.com/Kamiooorek/myDLTS/assets/37832419/1e0d7371-c7a5-4052-8d5d-e42a03dada4b)
![lakeshore331_2](https://github.com/Kamiooorek/myDLTS/assets/37832419/357cd5b0-cbfd-4f04-a41d-984090d896f9)

2. Okay we tried out some things last week. So we are able now to connect to the MFIA instrument and perform for example the CV measurement! We made it possible by not starting up the LabOne. Nevertheless, there is still a minor issue, that the LabView Api Version of myDLTS and our MFIA are different (22 vs 24).
![API_Mismatch](https://github.com/Kamiooorek/myDLTS/assets/37832419/6fd9e228-0ae1-4ebf-8dc1-86ddd4d5948a)

Here is the settings.xml file: [setting.xml.txt](https://github.com/Kamiooorek/myDLTS/files/15159922/setting.xml.txt)

Thank you for the support, best regards,
Malte

**Comment by Kamiooorek** [comment]
Hi!
I'm happy to see we're getting closer to have your setup working. 😊

1. In your 'settings.xml' file I can see, that you've entered the 'VISA name' as "LakeShore331". which would be _Name_ parameter in the screen capture. VISA library used in LabVIEW does not see this parameter and accepts only the parameter visible as _VISA-Resourcename_ (GPIB0::12::INSTR in your case). The field in the myDLTS settings should also let you choose a proper value from a drop-down list (loading can take some time), if it doesn't let you do that, something else might also be wrong.
![Settings](https://github.com/Kamiooorek/myDLTS/assets/102614102/28d0b631-61bf-4854-bcff-a92e1dc7b0c5)
I've also noticed that you had selected "Custom" type of controller instead of the "LakeShore331" - please select the LakeShore tab before saving the settings. The tab selection determines which type of controller will be connected.

2. Since you've successfully managed to measure some CV sweeps, I think that the version mismatch can be ignored. If it won't work, you can downgrade the MFIA firmware (from the older LabOne). We'll upgrade the API version used by the myDLTS app in the future.

Sincerely,
Adrian Kaim

**Comment by MaddoW** [comment]
Hey!

The connection now works, when we enter "GPIB0::12::INSTR" instead of "LakeShore331". When the list gets refreshed, it shows anyway only LakeShore331. We could now set the setpoint etc. So basically we are now ready to measure! 

So both problems are succesfulyl solved! :) Thank you so much.

We recognized, that the "Save shutdown checkbox" keeps deselecting itself after reopening the "Settings" window. Maybe thats a new issue?
![safely_shutdown](https://github.com/Kamiooorek/myDLTS/assets/37832419/2c373827-7d62-4896-804e-4dc188a97c84)

Best regards,
Malte

**Comment by Kamiooorek** [comment]
Hi!
I'm glad it's working! 😁
I've located the root of the automatic MFIA shutdown problem - both check-boxes write to the user compensation property. I've fixed the code for the future releases. In the meantime, if you want to use this feature just edit the 'settings.xml' file and change `<Shut_down_gracefully>false</Shut_down_gracefully>` to `<Shut_down_gracefully>true</Shut_down_gracefully>`.
Since everything in this thread seams to be fixed, I'll mark this issue as closed.
Sincerely,
Adrian Kaim
